carblog/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
namespace carblog.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminHomeController : Controller
    {
        CarblogEntities cbd = new CarblogEntities();
        // GET: Admin/Home
        public ActionResult AdminIndex()
        {
            return View();
        }
        public ActionResult Kullanicilar()
        {
            var kullaniciadi = cbd.Kayit.OrderByDescending(x => x.KullaniciAdi);
            return View(kullaniciadi);
        }
        public ActionResult Add()
        {
            return View();
        }

        public ActionResult AddUser(Kayit model)
        {
            if(ModelState.IsValid)
            {
                Kayit kayit = new Kayit();
                kayit.AdSoyad=model.AdSoyad;
                kayit.EMail=model.EMail;
                kayit.KullaniciAdi=model.KullaniciAdi;
                kayit.Password=model.Password;
                cbd.Kayit.Add(model);
                cbd.SaveChanges();
            }
            return RedirectToAction("AdminIndex");
        }

        [HttpGet]
        public ActionResult Edit(string KullaniciAdi)
        {
           var model = cbd.Kayit.Find(KullaniciAdi);
            //cbd.Kayit.FirstOrDefault(x => x.KullaniciAdi == KullaniciAdi);
            return View();
        }

        [HttpPost]
        public ActionResult Edit(Kayit model)
        {
            if(ModelState.IsValid)
            {
                cbd.Kayit.Attach(model);
                cbd.Entry(model).State = System.Data.Entity.EntityState.Modified;
                cbd.SaveChanges();
            }
            return View();
        }

        public ActionResult Delete(string KullaniciAdi)
        {
            var model = cbd.Kayit.Find(KullaniciAdi);
            return View(model);
        }

        public ActionResult DeleteConfirm(string KullaniciAdi)
        {
            var model = cbd.Kayit.Find(KullaniciAdi);
            cbd.Kayit.Remove(model);
            cbd.SaveChanges();
            return RedirectToAction("AdminIndex");
        }
    }
}

carblog/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CarBlog</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/custom")
    @Scripts.Render("~/bundles/modernizr")

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Favicons -->
    <link rel="shortcut icon" href="/Content/img/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="/Content/img/favicon.ico">

    <!-- Google fonts styles -->
    <link rel="stylesheet" id="google-fonts-Roboto-css" href="http://fonts.googleapis.com/css?family=Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic&amp;ver=3.9.1" type="text/css" media="all">
    <link rel="stylesheet" id="google-fonts-Playfair+Display-css" href="http://fonts.googleapis.com/css?family=Playfair+Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic&amp;ver=3.9.1" type="text/css" media="all">
    <!-- Aside styles -->
    <link rel="stylesheet" id="font-awesome-css" href="/Content/styles/font-awesome.min.css" type="text/css" media="screen">
    <link rel="stylesheet" id="pagebuild-css" href="/Content/styles/pagebuild.css" type="text/css" media="screen">
    <link rel="stylesheet" id="ux-aside-css" href="/Content/styles/style.css" type="text/css" media="screen">
    <link rel="stylesheet" id="icons-css" href="/Content/styles/icons.css" type="text/css" media="screen">

    <!-- Jquery Lib version 2.1.4 -->
    <script type="text/javascript" src="~/Scripts/jquery-2.1.4.min.js"></script>

    <!-- IE hack -->
    <!--[if lte IE 9]>
    <link rel='stylesheet' id='cssie'  href='/Content/styles/ie.css' type='text/css' media='screen' />
    <![endif]-->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="./js/ie.js"></script>
    <link rel='stylesheet' id='cssie8'  href='/Content/styles/ie8.css' type='text/css' media='screen' />
    <![endif]-->
    <!--[if lte IE 7]>
    <div style="width: 100%;" class="messagebox_orange">Your browser is obsolete and does not support this webpage. Please use newer version of your browser or visit <a href="http://www.ie6countdown.com/" target="_new">Internet Explorer 6 countdown page</a>  for more information. </div>
    <![endif]-->
</head>
<body class="home page page-template-default responsive-ux boxed-line aside-layout-ux">
    <!-- Page Loading -->
    <div class="page-loading visible">
        <div class="page-loading-inn">
            <div class="page-loading-transform">
                <div class="ux-loading"></div>
                <div class="ux-loading-transform">
                    <div class="loading-dot1">&nbsp;</div>
                    <div class="loading-dot2">&nbsp;</div>
                </div>
                <div class="site-loading-logo centered-ux">CarBlog</div>
            </div>
        </div>
    </div>
    <!-- Jplayer -->
    <div id="jquery_jplayer" class="jp-jplayer"></div>

    <!--Mobile Header meta-->
    <div id="mobile-header-meta">

        <!--Search Form-->
        <form id="search_form" name="" method="get" class="search-form_header" action="http://ximudesign.com/aside/">
            <input type="text" onblur="if (this.value == '') {this.value = 'SEARCH';}" onfocus="if (this.value == 'SEARCH') {this.value = '';}" id="s" name="s" value="SEARCH" class="textboxsearch">
            <span class="submit-wrap">
                <input type="submit" value="" class="submitsearch" name="submitsearch">
                <i class="fa fa-long-arrow-right middle-ux"></i>
            </span>
        </form>

        <!--Social icons-->
        <div class="social-icons-sidebar">
            <a class="icons-sidebar-unit" href="https://twitter.com/" title="Follow us"><i class="fa fa-twitter-square"></i></a>
            <a class="icons-sidebar-unit" href="https://www.facebook.com/" title="Follow us"><i class="fa fa-facebook-square"></i></a>
            <a class="icons-sidebar-unit" href="https://www.plus.google.com/" title="Follow us"><i class="fa fa-google-plus-square"></i></a>
            <a class="icons-sidebar-unit" href="https://www.youtube.com/" title=""><i class="fa fa-youtube-square"></i></a>
            <a class="icons-sidebar-unit" href="#" title=""><i class="fa fa-vimeo-square"></i></a>
        </div>
        <div class="mobile-meta-con">
            <div class="copyright">Copyright carblog.azurewebsites.net</div>
        </div>
        <!--End header-info-mobile-->
    </div>
    <!--End mobile-header-meta-->
    <div id="wrap">
        <!--Sidaber-->
        <aside id="sidebar" class="sidebar_hide">
            <div id="sidebar-trigger">
                <div class="menu-icon"><i class="icon-m-menu"></i></div>
            </div>
            <!--End sidebar-trigger-->
            <div class="sidebar-main">

                <!--Logo-->
                <h1 id="logo">CarBlog</h1>

                <!--Menu-->
                <nav id="navi" class=" clearfix">
                    <div id="navi_wrap" class="menu-demo-menu-container">
                        <ul class="menu">
                            <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                            <li>@Html.ActionLink("İletişim", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Hakkımızda","About","Home")</li>
                            <li>@Html.Partial("_AdminLoginPartial")</li>
                        </ul>
                    </div>
                    <!--End #navi_wrap-->
                </nav>
                <!-- End Menu -->
                <div class="sidebar-bottom-wrap">
                    <form id="search_form_1" name="" method="get" class="search-form_header" action="#">
                        <input type="text" onblur="if (this.value == '') {this.value = 'SEARCH';}" onfocus="if (this.value == 'SEARCH') {this.value = '';}" id="search" name="search" value="SEARCH" class="textboxsearch">
                        <span class="submit-wrap"><input type="submit" value="" class="submitsearch" name="submitsearch"><i class="fa fa-long-arrow-right middle-ux"></i></span>
                    </form>
                    <!--Social icons-->
                    <div class="social-icons-sidebar">
                        <a class="icons-sidebar-unit" href="https://twitter.com/" title="Follow us"><i class="fa fa-twitter-square"></i></a>
                        <a class="icons-sidebar-unit" href="https://www.facebook.com/" title="Follow us"><i class="fa fa-facebook-square"></i></a>
                        <a class="icons-sidebar-unit" href="#" title=""><i class="fa fa-google-plus-square"></i></a>
                        <a class="icons-sidebar-unit" href="https://www.youtube.com/" title=""><i class="fa fa-youtube-square"></i></a>
                    </div>
                    <!--End Social icons-->
                    <div class="copyright">Copyright carblog.azurewebsites.net</div><!--End copyright-->
                </div>
                <!--END sidebar-bottom-wrap-->
            </div>
            <!--end sidebar-main-->
        </aside>
        <!--Header-->
        <header id="header" class="">
            <h1 id="logo-mobile">
            <a href="Home/Index"> CarBlog</a></h1>
        </header>
        <!--End Header-->
        @RenderBody()
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/custom")
        @RenderSection("scripts", required: false)
        <div id="hot-close-sidebar-touch"></div>
    </div>load
    <!--End #wrap-->  
        <div class="float-bar-inn-wrap">
            <div class="float-bar-inn">
            </div>
            <!--End float inn wrap-->
        </div><!--End float inn-->
        <div id="float-bar-triggler"><i class="float-bar-triggler-inn"></i></div>
    <!--End #float bar-->

    
</body>
</html>

carblog/Areas/Admin/Views/Shared/_AdminLoginPartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
    @Html.AntiForgeryToken()

    <ul class="menu">
        <li>
            @Html.ActionLink("Merhaba " + User.Identity.GetUserName() + "!", "AdminIndex", "AdminHome", routeValues: null, htmlAttributes: new { title = "Düzenle" })
        </li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>
    }
}
else
{
        <ul class="menu">
            <li>@Html.ActionLink("Kayıt Ol", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
            <li>@Html.ActionLink("Giriş Yap", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
        </ul>
}